export const state = {
  config: null,
  volume: null,
  crisis: null,
  crisisId: "",
  crisisSeq: 0,
  active: null,
  page: "volume",
  lens: "world",
  perspective: null,
  world: null,
  archive: [],
  history: null,
  replay: null,
  replayLens: "then",
  replayActor: "",
  busy: false,
  activity: null,
  operationSeq: 0,
  viewSeq: 0,
  draftDecision: "",
  notice: "",
  error: "",
};
