export const state = {
  config: null,
  volume: null,
  active: null,
  page: "volume",
  world: null,
  lifetimes: null,
  selectedLifetime: "",
  follow: null,
  desk: null,
  archive: [],
  selectedArchive: "",
  archiveDetail: null,
  selectedReplayLifetime: "",
  busy: false,
  notice: "",
  error: "",
};
